# Generated by Django 2.2.27 on 2022-03-16 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
                ('docfile', models.FileField(upload_to='static/%Y/%m/%d', validators=[django.core.validators.validate_image_file_extension], verbose_name='Image')),
            ],
        ),
    ]
