# Generated by Django 4.0.4 on 2022-04-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialStockApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
