# Generated by Django 4.0.4 on 2022-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialStockApp', '0002_alter_materialtype_name_alter_stock_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='materialType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='MaterialType',
        ),
    ]
